# This handles the loading of my automations
#
# https://www.home-assistant.io/docs/automation/
#

# This include allows for UI-base automations.
automation: !include ../automations.yaml

# This one loads automations defined here in YAML.
automation mine: !include_dir_merge_list ../automations
