# Lovelace component for confuring the UI.
#
# https://www.home-assistant.io/lovelace/
# https://www.home-assistant.io/lovelace/dashboards-and-views
#
lovelace:
  # Either 'yaml' or 'storage'. I'm specifying storage here so I have one
  # 'Overview' dashboard that's configurable via the UI for quick messing
  # around. More permanent YAML dashboards are stored in ../dashboards.
  mode: storage

  # YAML dashboards are stored here:
  dashboards: !include ../dashboards/dashboards.yaml
