# yamllint disable rule:line-length
homeassistant:
  customize:
    sensor.beam_throughput_down:
      friendly_name: 'Beam download throughput'
      icon: mdi:download
    sensor.beam_throughput_up:
      friendly_name: 'Beam upload throughput'
      icon: mdi:upload
    sensor.centurylink_throughput_down:
      friendly_name: 'CenturyLink download throughput'
      icon: mdi:download
    sensor.centurylink_throughput_up:
      friendly_name: 'CenturyLink upload throughput'
      icon: mdi:upload

sensor:
  - platform: snmp
    name: snmp_wan_beam_in
    host: 192.168.10.1
    baseoid: 1.3.6.1.2.1.2.2.1.10.4

  - platform: snmp
    name: snmp_wan_beam_out
    host: 192.168.10.1
    baseoid: 1.3.6.1.2.1.2.2.1.16.4

  - platform: snmp
    name: snmp_wan_centurylink_in
    host: 192.168.10.1
    baseoid: 1.3.6.1.2.1.2.2.1.10.3

  - platform: snmp
    name: snmp_wan_centurylink_out
    host: 192.168.10.1
    baseoid: 1.3.6.1.2.1.2.2.1.16.3

  - platform: template
    sensors:
      beam_throughput_down_raw:
        friendly_name: 'Beam download throughput raw'
        value_template: '{{ ((states.input_number.beam_download_traffic_delta.state | float ) / 1000000 ) | round(2) }}'
        unit_of_measurement: 'Mbps'

  - platform: template
    sensors:
      beam_throughput_up_raw:
        friendly_name: 'Beam upload throughput raw'
        value_template: '{{ ((states.input_number.beam_upload_traffic_delta.state | float ) / 1000000 ) | round(2) }}'
        unit_of_measurement: 'Mbps'

  - platform: template
    sensors:
      centurylink_throughput_down_raw:
        friendly_name: 'CenturyLink download throughput raw'
        value_template: '{{ ((states.input_number.centurylink_download_traffic_delta.state | float ) / 1000000 ) | round(2) }}'
        unit_of_measurement: 'Mbps'

  - platform: template
    sensors:
      centurylink_throughput_up_raw:
        friendly_name: 'CenturyLink upload throughput raw'
        value_template: '{{ ((states.input_number.centurylink_upload_traffic_delta.state | float ) / 1000000 ) | round(2) }}'
        unit_of_measurement: 'Mbps'

  - platform: statistics
    name: 'Beam throughput down'
    entity_id: sensor.beam_throughput_down_raw

  - platform: statistics
    name: 'Beam throughput up'
    entity_id: sensor.beam_throughput_up_raw

  - platform: statistics
    name: 'CenturyLink throughput down'
    entity_id: sensor.centurylink_throughput_down_raw

  - platform: statistics
    name: 'CenturyLink throughput up'
    entity_id: sensor.centurylink_throughput_up_raw

input_number:
  beam_download_traffic_delta:
    name: "Beam download traffic delta"
    initial: 0
    min: 0
    max: 10000000000000

  beam_upload_traffic_delta:
    name: "Beam upload traffic delta"
    initial: 0
    min: 0
    max: 10000000000000

  centurylink_download_traffic_delta:
    name: "CenturyLink download traffic delta"
    initial: 0
    min: 0
    max: 10000000000000

  centurylink_upload_traffic_delta:
    name: "CenturyLink upload traffic delta"
    initial: 0
    min: 0
    max: 10000000000000

automation:
  - id: snmp_monitor_beam_download_traffic
    alias: Monitor beam download traffic
    trigger:
      platform: state
      entity_id: sensor.snmp_wan_beam_in
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.beam_download_traffic_delta
          value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'

  - id: snmp_monitor_beam_upload_traffic
    alias: Monitor beam upload traffic
    trigger:
      platform: state
      entity_id: sensor.snmp_wan_beam_out
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.beam_upload_traffic_delta
          value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'

  - id: snmp_monitor_centurylink_download_traffic
    alias: Monitor centurylink download traffic
    trigger:
      platform: state
      entity_id: sensor.snmp_wan_centurylink_in
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.centurylink_download_traffic_delta
          value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'

  - id: snmp_monitor_centurylink_upload_traffic
    alias: Monitor centurylink upload traffic
    trigger:
      platform: state
      entity_id: sensor.snmp_wan_centurylink_out
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.centurylink_upload_traffic_delta
          value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'
