# The logger integration lets you define the level of logging activities
# in Home Assistant.
#
# I use this to reduce error messages for specific things,
# so I can focus on log messages that matter to me.
#
logger:
  default: info
  logs:
    # For when I experience slow startups
    # I can enable this to check out what is going on
    # homeassistant.setup: debug
    influxdb: debug

