#
# This integration uses the Ambient Weather API to retrieve
# data from our weather station.
#
ambient_station:
  api_key: !secret ambient_api_key
  app_key: !secret ambient_app_key_2

homeassistant:
  customize:
    sensor.mpws2000_hourly_rain_rate:
      friendly_name: Hourly rain
      icon: mdi:weather-pouring

    sensor.mpws2000_daily_rain:
      friendly_name: Daily rain
      icon: mdi:weather-pouring

    sensor.mpws2000_weekly_rain:
      friendly_name: Weekly rain
      icon: mdi:weather-pouring

    sensor.mpws2000_monthly_rain:
      friendly_name: Monthly rain
      icon: mdi:weather-pouring

    sensor.mpws2000_yearly_rain:
      friendly_name: Yearly rain
      icon: mdi:weather-pouring

    sensor.mpws2000_wind_speed:
      friendly_name: Wind speed
      icon: mdi:weather-windy

    sensor.mpws2000_wind_gust:
      friendly_name: Wind gust
      icon: mdi:weather-windy

    sensor.mpws2000_inside_temp:
      friendly_name: Indoor temp
      icon: mdi:home-outline

    sensor.mpws2000_dew_point:
      friendly_name: Dew point
      icon: mdi:water-percent

    sensor.mpws2000_max_gust:
      friendly_name: Max gust
      icon: mdi:weather-windy

    sensor.mpws2000_wind_dir:
      friendly_name: Wind direction
      icon: mdi:compass-outline
