# The logger integration lets you define the level of logging activities
# in Home Assistant.
#
logger:
  default: info
  logs:
    # For when I experience slow startups
    # I can enable this to check out what is going on
    # homeassistant.setup: debug
    influxdb: debug

    # Debugging aux heat issue with ecobee
    ecobee: debug

