# Lovelace component for confuring the UI.
#
# https://www.home-assistant.io/lovelace/
# https://www.home-assistant.io/lovelace/dashboards-and-views
#
lovelace:
  # Either 'yaml' or 'storage'.
  mode: yaml

  # YAML dashboards are stored here:
  dashboards: !include ../dashboards/dashboards.yaml

  resources: !include ../dashboards/resources.yaml
