octoprint:
  host: 192.168.10.34
  api_key: !secret octoprint_api_key
  name: Ender 3 V2
  bed: true
  number_of_tools: 1

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

sensor:
  - platform: template
    sensors:
      ender_3_v2_time_elapsed_friendly:
        friendly_name: Ender 3 V2 time elapsed
        value_template: >
          {{ states('sensor.ender_3_v2_time_elapsed') | int | timestamp_custom('%H:%M:%S', 0) }}
      ender_3_v2_time_remaining_friendly:
        friendly_name: Ender 3 V2 time remaining
        value_template: >
          {{ states('sensor.ender_3_v2_time_remaining') | int | timestamp_custom('%H:%M:%S', 0) }}

      ender_3_v2_time_complete:
        friendly_name: Ender 3 V2 time complete
        value_template: >
          {{ (now() + timedelta(0,states('sensor.ender_3_v2_time_remaining') | int)).strftime("%H:%M:%S") }}

camera:
  - platform: mjpeg
    name: Ender 3 V2
    still_image_url: http://192.168.10.34/webcam/?action=snapshot
    mjpeg_url: http://192.168.10.34/webcam/?action=stream

homeassistant:
  customize:
    sensor.ender_3_v2_actual_bed_temp:
      unit_of_measurement: C
    sensor.ender_3_v2_target_bed_temp:
      unit_of_measurement: C
    sensor.ender_3_v2_actual_tool0_temp:
      unit_of_measurement: C
    sensor.ender_3_v2_target_tool0_temp:
      unit_of_measurement: C

    sensor.ender_3_v2_time_elapsed_friendly:
      icon: mdi:clock-start

    sensor.ender_3_v2_time_remaining_friendly:
      icon: mdi:clock-end

    sensor.ender_3_v2_time_complete:
      icon: mdi:clock-check-outline

