#
# This integration connects the main HA instance to a remote hassio instance
# running on a Raspberry Pi in our barn.
#
remote_homeassistant:
  instances:
    - host: 192.168.10.14
      port: 8123
      access_token: !secret barn_hassio_token
      entity_prefix: barn_
      include:
        domains:
          - switch
          - sensor
      exclude:
        domains:
          - persistent_notification
        entities:
          - zwave.aeotec_zw090_zstick_gen5_us
          - zwave.aeotec_dsc06106_smart_energy_switch
      subscribe_events:
        - state_changed
        - service_registered
        - zwave.network_ready
        - zwave.node_event

    - host: 192.168.10.33
      port: 8123
      access_token: !secret zwave_hassio_token
      entity_prefix: zw_
      include:
        domains:
          - binary_sensor
          - light
          - sensor
          - switch
      subscribe_events:
        - state_changed
        - service_registered
        - zwave.network_ready
        - zwave.node_event
        - zha_event

sensor:
  - platform: template
    sensors:
      zw_raspberry_pi_temperature_c:
        friendly_name: "ZWave Raspberry Pi temperature (C)"
        value_template: '{{ ((states.sensor.zw_raspberry_pi_temperature.state | float - 32) * 5 / 9 ) | round(1) }}'
        unit_of_measurement: '°C'
