# The Microsoft text-to-speech platform uses the TTS engine of
# the Azure Cognitive Services Speech Service to read text with
# a natural sounding voice. You'll need a free Azure subscription
# to use it, more info in the HA docs.
#
# https://www.home-assistant.io/integrations/microsoft
#
tts:
  platform: microsoft
  api_key: !secret microsoft_speech_api_key

  # Set the voice language.
  language: en-us

  # Cache voice files to a local storage.
  cache: true

  # Path to a location for caching the tts files.
  cache_dir: /tmp/tts

  # Time to hold (in seconds) the voice data inside memory for fast play
  # on a media player. (min 60, max 57600)
  time_memory: 300
