views:
  - badges: []
    cards:
      - cards:
          - content: '### Front room'
            type: markdown
          - cards:
              - entity: switch.front_room_floor_lamp
                hold_action:
                  action: more-info
                icon_height: 36px
                name: Floor lamp
                show_icon: true
                show_name: true
                tap_action:
                  action: toggle
                type: button
              - entity: light.bookshelf_lights
                hold_action:
                  action: more-info
                icon: 'mdi:track-light'
                icon_height: 36px
                name: Bookshelves
                show_icon: true
                show_name: true
                tap_action:
                  action: toggle
                type: button
            type: horizontal-stack
          - content: '### Living room'
            type: markdown
          - cards:
              - entity: light.sofa_lights
                hold_action:
                  action: more-info
                icon: 'mdi:wall-sconce-flat'
                icon_height: 36px
                name: Sofa
                show_icon: true
                show_name: true
                tap_action:
                  action: toggle
                type: button
              - entity: switch.end_table_lamp
                hold_action:
                  action: more-info
                icon: 'mdi:lamp'
                icon_height: 36px
                name: End table
                show_icon: true
                show_name: true
                tap_action:
                  action: toggle
                type: button
              - entity: switch.living_room_lamp
                hold_action:
                  action: more-info
                icon: 'mdi:floor-lamp'
                icon_height: 36px
                name: Floor lamp
                show_icon: true
                show_name: true
                tap_action:
                  action: toggle
                type: button
            type: horizontal-stack
          - content: '### Outdoor'
            type: markdown
          - cards:
              - entity: light.porch_lights
                hold_action:
                  action: more-info
                icon: 'mdi:dome-light'
                icon_height: 36px
                name: Porch
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.front_entry_lights
                hold_action:
                  action: more-info
                icon: 'mdi:coach-lamp'
                icon_height: 36px
                name: Entry
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: switch.aeotec_cord
                hold_action:
                  action: more-info
                icon: 'mdi:string-lights'
                icon_height: 36px
                name: String
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: switch.patio_lights
                hold_action:
                  action: more-info
                icon: 'mdi:coach-lamp'
                icon_height: 36px
                name: Patio
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: switch.barn_barn_front_lights
                hold_action:
                  action: more-info
                icon: 'mdi:outdoor-lamp'
                icon_height: 36px
                name: Barn
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
            type: horizontal-stack
          - content: '### Floodlights'
            type: markdown
          - cards:
              - entity: switch.flood_back
                hold_action:
                  action: more-info
                icon: 'mdi:car-light-high'
                icon_height: 36px
                name: Back
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: switch.flood_garage
                hold_action:
                  action: more-info
                icon: 'mdi:car-light-high'
                icon_height: 36px
                name: Garage
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: switch.flood_side
                hold_action:
                  action: more-info
                icon: 'mdi:car-light-high'
                icon_height: 36px
                name: Side
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: switch.barn_barn_flood_lights
                hold_action:
                  action: more-info
                icon: 'mdi:car-light-high'
                icon_height: 36px
                name: Barn
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
            type: horizontal-stack
        type: vertical-stack
    icon: 'mdi:home-assistant'
    path: main
    title: ''
  - badges: []
    cards:
      - cards:
          - cards:
              - entity: sensor.my_weather_station_temp
                graph: line
                name: Temp
                type: sensor
              - entity: sensor.my_weather_station_humidity
                graph: line
                name: Humidity
                type: sensor
              - entity: sensor.my_weather_station_rel_pressure
                graph: line
                name: Pressure
                type: sensor
            type: horizontal-stack
          - cards:
              - entity: sensor.my_weather_station_wind_speed
                graph: line
                icon: 'mdi:weather-windy'
                name: Wind
                type: sensor
              - entity: sensor.my_weather_station_wind_gust
                graph: line
                icon: 'mdi:weather-windy'
                name: Gust
                type: sensor
            type: horizontal-stack
          - cards:
              - entity: sensor.my_weather_station_hourly_rain_rate
                graph: line
                icon: 'mdi:weather-pouring'
                name: Rate
                type: sensor
              - entity: sensor.my_weather_station_daily_rain
                graph: line
                icon: 'mdi:weather-pouring'
                name: Daily
                type: sensor
            type: horizontal-stack
        type: vertical-stack
    icon: 'mdi:weather-partly-snowy-rainy'
    title: ''
  - badges: []
    cards:
      - entity: climate.main_floor
        name: Main Floor
        theme: Backend-selected
        type: thermostat
      - entity: climate.upstairs
        name: Upstairs
        theme: Backend-selected
        type: thermostat
    icon: 'mdi:thermostat'
    panel: false
    path: ''
    title: ''
  - badges: []
    cards:
      - entities:
          - entity: lock.front_door_lock
            name: Front door
          - entity: lock.porch_door_lock
            name: Porch door
          - entity: lock.basement_door_lock
            name: Basement door
          - entity: sensor.front_door_lock_battery
            name: Front door battery
          - entity: sensor.porch_door_lock_battery
            name: Porch door battery
          - entity: sensor.basement_door_lock_battery
            name: Basement door battery
        title: Doors
        type: entities
    icon: 'mdi:door-closed-lock'
    path: ''
    title: ''
