- platform: template
  covers:
    garage_door_1:
      device_class: garage
      friendly_name: "Garage door 1"
      value_template: >-
        {% if is_state('binary_sensor.zw_garage_door_1_sensor', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      open_cover:
        - condition: state
          entity_id: binary_sensor.zw_garage_door_1_sensor
          state: "on"
      close_cover:
        - condition: state
          entity_id: binary_sensor.zw_garage_door_1_sensor
          state: "off"

    garage_door_2:
      device_class: garage
      friendly_name: "Garage door 2"
      value_template: >-
        {% if is_state('binary_sensor.zw_garage_door_2_sensor', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      open_cover:
        - condition: state
          entity_id: binary_sensor.zw_garage_door_2_sensor
          state: "on"
      close_cover:
        - condition: state
          entity_id: binary_sensor.zw_garage_door_2_sensor
          state: "off"
