- alias: Turn on bookshelf lights when front room lamp turned on
  trigger:
    platform: state
    entity_id: switch.front_room_floor_lamp
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.zw_bookshelf_lights
      brightness_pct: 100

- alias: Turn off bookshelf lights when front room lamp turned off
  trigger:
    platform: state
    entity_id: switch.front_room_floor_lamp
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.zw_bookshelf_lights

