- alias: Turn on spare room light at night
  trigger:
    platform: time
    at: '20:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.zw_spare_room_lamp
  mode: single

- alias: Toggle nightstand lamp on Flic click
  trigger:
    platform: webhook
    webhook_id: flic_spare-room_click
  action:
    service: switch.toggle
    entity_id: switch.zw_spare_room_lamp
  mode: single

- alias: Toggle dresser lamp on Flic double-click
  trigger:
    platform: webhook
    webhook_id: flic_spare-room_doubleclick
  action:
    service: switch.toggle
    entity_id: switch.spare_room_dresser
  mode: single

- alias: Turn off all lights on Flic hold
  trigger:
    platform: webhook
    webhook_id: flic_spare-room_hold
  action:
    - service: switch.turn_off
      entity_id: switch.zw_spare_room_lamp
    - service: switch.turn_off
      entity_id: switch.spare_room_dresser
  mode: single

- id: spare_room_dresser_zha
  alias: Spare room dresser (zigbee)
  trigger:
  - event_data:
      command: single
      unique_id: "00:15:8d:00:02:82:cf:e3:1:0x0012"
    event_type: zha_event
    platform: event
  action:
    - service: light.toggle
      entity_id: light.spare_room_dresser_lamp
