# Handles clicks for the basement counter button
- id: aqara_button_basement_counter
  alias: Aqara wireless remote basement counter
  mode: restart

  trigger:
    platform: event
    event_type: zha_event

  condition:
    condition: template
    value_template: '{{ trigger.event.data.device_ieee == "00:15:8d:00:02:83:ef:96" }}'

  action:
    - choose:
        # Single click
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "single" }}'
          sequence:
            - service: light.toggle
              data:
                entity_id: light.zw_basement_counter_lights
                brightness_pct: 100

        # Double click
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "double" }}'
          sequence:
            - service: light.toggle
              data:
                entity_id: light.zw_basement_counter_lights
                brightness_pct: 50

