# This is a single automation to handle multiple event types from the Aqara "magic" cube.
# Using a single automation for multiple events is genius but it wasn't my idea,
# it came from here: https://gist.github.com/niro1987/2f49fa978b1afa2a2ea8eb83cc32e97f

- id: aqara_cube
  alias: Aqara cube remote
  mode: restart

  trigger:
    platform: event
    event_type: zha_event

  condition:
    condition: template
    value_template: '{{ trigger.event.data.device_ieee == "00:15:8d:00:05:1d:fd:1d" }}'

  action:
    - choose:
        # Rotate left/right (the relative_degrees arg will be negative for rotate_right events)
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command.startswith("rotate_") }}'
          sequence:
            - service: light.turn_on
              data_template:
                entity_id: light.basement_office
                brightness_step_pct: '{{ trigger.event.data.args.relative_degrees | float / 3 }}'
            - service: light.turn_on
              data_template:
                entity_id: light.zw_basement_desk_lamp_color
                brightness_step_pct: '{{ trigger.event.data.args.relative_degrees | float / 3 }}'

        # Shake
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "shake" }}'
          sequence:
            - service: light.turn_off
              entity_id: light.basement_office
            - service: light.turn_off
              entity_id: light.zw_basement_desk_lamp_color
