# Handles clicks for the basement blind buttons
- id: basement_blind_buttons
  alias: Tradfri wireless remote basement blinds
  mode: restart

  trigger:
    platform: event
    event_type: zha_event

  condition:
    condition: template
    value_template: '{{ trigger.event.data.device_ieee == "84:fd:27:ff:fe:9f:4f:bf" or trigger.event.data.device_ieee == "80:4b:50:ff:fe:d5:6d:84" }}'

  action:
    - choose:
        # Up click
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "up_open" }}'
          sequence:
            - service: cover.open_cover
              data:
                entity_id: cover.basement_blinds

        # Down click
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "down_close" }}'
          sequence:
            - service: cover.close_cover
              data:
                entity_id: cover.basement_blinds

        # Stop
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "stop" }}'
          sequence:
            - service: cover.stop_cover
              data:
                entity_id: cover.basement_blinds

