- alias: Turn barn lights on in the morning
  trigger:
    platform: time
    at: 05:30
  action:
    service: switch.turn_on
    entity_id: switch.barn_front_down_lights

- alias: Turn barn lights off in the morning
  trigger:
    platform: sun
    event: sunrise
    offset: +01:00:00
  action:
    service: switch.turn_off
    entity_id: switch.barn_front_down_lights

- alias: Turn living room floor lamp off in the morning
  description: Turn living room floor lamp off in the morning
  trigger:
    platform: sun
    event: sunrise
    offset: +00:30:00
  action:
    service: light.turn_off
    entity_id: light.zw_living_room_floor_lamp_color
  mode: single
