- alias: Turn on basement stairs light on motion
  trigger:
    platform: state
    entity_id: binary_sensor.zw_basement_stairs_multisensor_motion
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.zw_basement_stair_lights
      brightness_pct: 40
  mode: single

- alias: Turn off basement stairs light after motion end
  trigger:
    platform: state
    entity_id: binary_sensor.zw_basement_stairs_multisensor_motion
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.zw_basement_stair_lights
  mode: single

