# Handles the Tradfri remote in the mudroom
- id: tradfri_mudroom
  alias: Mudroom Tradfri remote
  mode: restart

  trigger:
    platform: event
    event_type: zha_event

  condition:
    condition: template
    value_template: '{{ trigger.event.data.device_id == "968920893415e9a625008c551e42efdb" }}'

  action:
    - choose:
        # Toggle
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "toggle" }}'
          sequence:
            - service: light.toggle
              entity_id: light.mudroom_lights

        # Hold
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "press" }}'
          sequence:
            - service: light.turn_off
              entity_id: light.mudroom_lights
