camera.basement:
  friendly_name: Basement storage camera

media_player.basement:
  friendly_name: Basement Sonos

sensor.zw_basement_stairs_multisensor_relative_humidity:
  icon: mdi:water-percent

switch.3d_printer_power:
  icon: mdi:power
