# Welcome to my Home Assistant configuration!
#
# Basically, each file in the repository does 1 thing only;
# this configuration.yaml file is only used to bootstrap the system.
#
homeassistant:
  # Load packages
  packages: !include_dir_named integrations
