# Welcome to my Home Assistant configuration!
#
# Most files in this configuration do only one thing, or a short list
# of closely-related things. This configuration.yaml file bootstraps
# the setup by loading each integration from its file in the
# /config/integrations folder.
#

# Configure a default setup of Home Assistant (frontent, api, etc)
default_config:

# Load packages for everything else
homeassistant:
  packages: !include_dir_named integrations
