- alias: 'Basement lights to Off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.basement_lights
      to: 'Off'
  action:
    - service: switch.turn_off
      entity_id: switch.basement_desk_lamp
    - service: light.turn_off
      entity_id: light.basement_office
    - service: light.turn_off
      entity_id: light.strip_light_1

- alias: 'Basement lights to On'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.basement_lights
      to: 'On'
  action:
    - service: switch.turn_on
      entity_id: switch.basement_desk_lamp
    - service: light.turn_on
      data:
        entity_id: light.basement_office
        brightness: 255

    # Added cheer
    - service: light.turn_on
      data:
        entity_id: light.strip_light_1
        color_name: green

- alias: 'Basement lights to Working'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.basement_lights
      to: 'Working'
  action:
    - service: switch.turn_on
      entity_id: switch.basement_desk_lamp
    - service: light.turn_on
      data:
        entity_id: light.basement_office
        brightness: 50

