---
name: Home Assistant CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .

  remarklint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@v1
      - name: Running MarkdownLint
        uses: nosborn/github-action-markdown-cli@1.1.1
        with:
          files: .
          config_file: .markdownlint.yaml

  home_assistant_stable:
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./config
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --config ./config/ --script check_config  --info all
